configuration: Release

#init:
#  - git config --global core.autocrlf true
  
build:
  project: AV-GH-release-notes.sln
  verbosity: minimal

after_build:
 - D:\Prog\Github\AV-GH-release-notes\PushToAVEnv\bin\Release\PushToAVEnv.exe

test: off
  
deploy:
  - provider: GitHub
    auth_token:
      secure: WaNF2IUzat+PQQqquLoaN43QIpnUsrYgSOGN3P5Tpy+A+ANOWQqvWE0eFA+XwmmX
    description: $(test_env_releasenotes)

