configuration: Release

#init:
#  - git config --global core.autocrlf true
  
before_build:
 - nuget restore SemanticReleaseNotesParser.sln
  
build:
#  roject: AV-GH-release-notes.sln
  project: SemanticReleaseNotesParser.sln
  verbosity: minimal

after_build:
 #- PushToAVEnv\bin\Release\PushToAVEnv.exe
  - SemanticReleaseNotesParser\bin\Release\SemanticReleaseNotesParser.exe -t=environment -f=markdown --debug

test: off
  
deploy:
  - provider: GitHub
    auth_token:
      secure: WaNF2IUzat+PQQqquLoaN43QIpnUsrYgSOGN3P5Tpy+A+ANOWQqvWE0eFA+XwmmX
    description: $(test_env_releasenotes)

